name: GitHub Actions Demo
run-name: Start Throughput Experiment ⏱️
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:github-actions
        version: 1.76.6

    - name: Tailscale SSH
      run: |
        ssh $USERNAME@$HOSTNAME -o "StrictHostKeyChecking no" 'whoami'
      env:
        USERNAME: ${{ secrets.EXPERIMENT_SERVER_USERNAME }}
        HOSTNAME: ${{ secrets.EXPERIMENT_SERVER }}
