# RESOURCES UTILIZED:
# https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
# https://tailscale.com/blog/2021-05-github-actions-and-tailscale
# https://stackoverflow.com/a/63030126
# https://unix.stackexchange.com/a/304864/635993
#
name: Throughput Experiments ⏱️
run-name: Start Throughput Experiment ⏱️
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:github-actions
        version: 1.76.6
    
    - name: Wake on LAN
      run: |
        ssh $USERNAME@$HOSTNAME -o "StrictHostKeyChecking no" \
          "wakeonlan '$MAC_ADDR' && sleep 15"
      env:
        USERNAME: ${{ secrets.RASPBERRY_PI_USERNAME }}
        HOSTNAME: ${{ secrets.RASPBERRY_PI }}
        MAC_ADDR: $${{ secrets.EXPERIMENT_SERVER_MAC_ADDR }}
        
    - name: Start the Experiment
      run: |
        ssh $USERNAME@$HOSTNAME -o "StrictHostKeyChecking no" \
          "tmux new -s github-actions -d 'sleep 60' && tmux ls"
      env:
        USERNAME: ${{ secrets.EXPERIMENT_SERVER_USERNAME }}
        HOSTNAME: ${{ secrets.EXPERIMENT_SERVER }}