name: GitHub Actions Demo
run-name: Start Throughput Experiment ⏱️
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:github-actions
        version: 1.76.6
    - name: ssh onto Experiment Server
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.EXPERIMENT_SERVER }}
        username: ${{ secrets.EXPERIMENT_SERVER_USERNAME }}
        password: ${{ secrets.EXPERIMENT_SERVER_PASSWORD }}
        script:
          echo "Hello World!"
